export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/discover',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  FEED: '/feed',
  SETTINGS: '/settings',
  FOR_ARTISTS: '/for-artists',
  PROFILE: (username: string) => `/profile/${username}`,
  FOLLOWERS: (username: string) => `/profile/${username}/followers`,
  FOLLOWING: (username: string) => `/profile/${username}/following`,
  LIKES: (username: string) => `/profile/${username}/likes`,
  TRACK: (trackId: string) => `/tracks/${trackId}`,
  PLAYLIST: (id: string) => `/playlist/${id}`,
  UPLOAD: '/upload',
  MY_TRACKS: '/my-tracks',
  LIBRARY: '/library',
  HISTORY: '/library?tab=history',
  LIBRARY_LIKES: '/library?tab=likes',
  SEARCH: '/search',
  TRENDING: '/discover',
  CHARTS: '/charts',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_CONTENT: '/admin/content',
  ADMIN_HEALTH: '/admin/health',
  MESSAGES: '/messages',
  NOTIFICATIONS: '/notifications',
  STATIONS: '/stations',
  ARTIST_PRO: '/artist-pro',
  PAYMENT: '/payment',
  SUBSCRIPTION: '/subscription',
} as const
