export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/home',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  FEED: '/feed',
  SETTINGS: '/settings',
  FOR_ARTISTS: '/for-artists',
  PROFILE: (username: string) => `/profile/${username}`,
  FOLLOWERS: (username: string) => `/profile/${username}/followers`,
  FOLLOWING: (username: string) => `/profile/${username}/following`,
  LIKES: (username: string) => `/profile/${username}/likes`,
  TRACK: (trackId: string) => `/tracks/${trackId}`,
  UPLOAD: '/upload',
  MY_TRACKS: '/my-tracks',
  LIBRARY: '/library',
  HISTORY: '/library?tab=history',
  LIBRARY_LIKES: '/library?tab=likes',
  NOTIFICATIONS: '/settings?tab=notifications',
} as const
